name: CI

on: push

permissions:
  contents: read

jobs:
  test:

    name: Build and test
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v6
    - uses: erlef/setup-beam@v1
      id: beam
      with:
        version-file: '.tool-versions'
        version-type: 'strict'

    - name: Restore dependencies cache
      uses: actions/cache@v5
      with:
        path: deps
        key: ${{ runner.os }}-mix-deps-${{ hashFiles('**/mix.lock') }}

    - name: Restore compilation cache
      uses: actions/cache@v5
      with:
        path: _build
        key: ${{ runner.os }}-mix-build-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-${{ hashFiles('**/mix.lock') }}

    - name: Set up Node.js for Playwright CI
      uses: actions/setup-node@6
      with:
        node-version: '24'

    - name: Install Playwright system dependencies
      run: sudo npx playwright install-deps
      working-directory: ./assets

    - name: Install Playwright browsers
      run : npx playwright install
      working-directory: ./assets

    - run: mix deps.get
    - run: mix deps.unlock --check-unused
    - run: mix compile --warnings-as-errors
    - run: mix format --check-formatted
    - run: mix test
